# Generated by Django 4.0 on 2023-03-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0012_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('photo', models.FileField(upload_to='Events/%Y/%m.%d/', verbose_name='Фото мероприятия')),
                ('text', models.TextField(verbose_name='текст')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('time', models.TimeField(verbose_name='Время мероприятия')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.customuser', verbose_name='Кто добавил')),
            ],
            options={
                'db_table': 'Events',
            },
        ),
    ]
