version: "3.9"

services:
  app:
    build:
      dockerfile: dockerfile
    entrypoint: sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn MainPartSiteDGU.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./MainPartSiteDGU/static:/app/static
      - ./MainPartSiteDGU/media:/app/media
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./MainPartSiteDGU/static:/static
      - ./MainPartSiteDGU/media:/media

  # нужно скачать -> docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
  # что бы можно было отправлять логи с проекта в loki
  grafana:
    image: grafana/grafana:9.2.15
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true # отключает авторизацию по паролю и выполняет вход анонимным пользователем
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # анонимный пользователь становится админом
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
volumes:
  static: