FROM python:3.10

WORKDIR /test/dj

COPY ./requirements.txt /test/dj
RUN pip install -r /test/dj/requirements.txt

COPY . /test/dj

EXPOSE 8000

CMD ["python", "manage.py", "migrate"]
CMD ["python", "manage.py", "runserver" , "0.0.0.0:8000"]