# Generated by Django 4.0 on 2022-08-11 15:23

import Students.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='статус')),
            ],
            options={
                'db_table': 'StatusStudent',
            },
        ),
        migrations.CreateModel(
            name='TypeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Направление')),
            ],
            options={
                'db_table': 'TypeCourse',
            },
        ),
        migrations.CreateModel(
            name='InfoStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('course', models.IntegerField(choices=[(1, '1-курс'), (2, '2-курс'), (3, '3-курс'), (4, '4-курс')], default=0)),
                ('photo_student', models.FileField(upload_to=Students.models.directory_path, verbose_name='фото студента')),
                ('social_status', models.BooleanField(verbose_name='социальная справка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.typecourse', verbose_name='Направление')),
                ('student_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Students.statusstudent', verbose_name='статус студента')),
            ],
            options={
                'db_table': 'InfoStudent',
            },
        ),
    ]
