# Generated by Django 4.0 on 2022-08-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='infostudent',
            table='InfoStudent',
        ),
        migrations.AlterModelTable(
            name='statusstudent',
            table='StatusStudent',
        ),
        migrations.AlterModelTable(
            name='typecourse',
            table='TypeCourse',
        ),
    ]
