# Generated by Django 4.0 on 2022-10-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='deta',
            new_name='date',
        ),
    ]
