# Generated by Django 4.0 on 2022-08-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeCourse',
            new_name='TypeDirection',
        ),
        migrations.AlterModelTable(
            name='typedirection',
            table='TypeDirection',
        ),
    ]
