# Generated by Django 4.0 on 2022-10-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_delete_personalroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.FileField(upload_to='Events/%Y/%m.%d/', verbose_name='Фото мероприятия'),
        ),
    ]
