# Generated by Django 4.0 on 2022-10-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_rename_first_name_infostudent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infostudent',
            name='course',
            field=models.CharField(choices=[('1', '1-курс'), ('1-1', '1-курс-академ'), ('1-2', '1-курс-магистратура'), ('2', '2-курс'), ('2-1', '2-курс-академ'), ('2-2', '2-курс-магистратура'), ('3', '3-курс'), ('3-1', '3-курс-академ'), ('4', '4-курс'), ('4-1', '4-курс-академ')], default='1', max_length=3, verbose_name='курс'),
        ),
    ]
