# Generated by Django 4.0 on 2022-10-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_alter_infostudent_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infostudent',
            name='social_status',
        ),
    ]
