# Generated by Django 4.0 on 2022-10-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_events_time_alter_events_date_alter_events_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время мероприятия'),
        ),
    ]
