# Generated by Django 4.0 on 2022-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_remove_infostudent_social_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infostudent',
            name='photo_student',
            field=models.FileField(default=None, upload_to='photo/%Y/%m.%d/', verbose_name='фото студента'),
        ),
    ]
