# Generated by Django 4.0 on 2022-10-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_alter_events_date_alter_events_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.customuser', verbose_name='Кто добавил'),
        ),
    ]
