# Generated by Django 4.0 on 2022-10-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infostudent',
            name='student_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.statusstudent', verbose_name='статус студента'),
        ),
    ]
