# Generated by Django 4.0 on 2022-10-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_alter_infostudent_photo_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infostudent',
            name='photo_student',
            field=models.FileField(default='default_img/default.png', upload_to='photo/%Y/%m.%d/', verbose_name='фото студента'),
        ),
    ]
