# Generated by Django 4.0 on 2022-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_alter_infostudent_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='infostudent',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФОИ'),
        ),
        migrations.AlterField(
            model_name='infostudent',
            name='end_social_reference',
            field=models.DateField(blank=True, null=True, verbose_name='дата завершения действия справки'),
        ),
        migrations.AlterField(
            model_name='infostudent',
            name='start_social_reference',
            field=models.DateField(blank=True, null=True, verbose_name='дата назначения справки'),
        ),
    ]
