# Generated by Django 4.0 on 2022-10-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_alter_infostudent_photo_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Сектор организации')),
            ],
            options={
                'db_table': 'OrganizationSector',
            },
        ),
        migrations.AddField(
            model_name='infostudent',
            name='organization',
            field=models.CharField(choices=[('К', 'КДМ'), ('П', 'ПРОФКОМ'), ('С', 'СНО'), ('Н', 'Нету')], default='Н', max_length=1, verbose_name='организация'),
        ),
        migrations.AddField(
            model_name='infostudent',
            name='organization_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.organizationsector', verbose_name='Сектор организации'),
        ),
    ]
