# Generated by Django 4.0 on 2022-10-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_organizationsector_infostudent_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infostudent',
            name='photo_social_reference',
            field=models.FileField(default='default_img/default.png', upload_to='social_reference/', verbose_name='Социальная справка'),
        ),
    ]
