# Generated by Django 4.0 on 2022-10-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_infostudent_photo_social_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='infostudent',
            name='end_social_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='дата завершения действия справки'),
        ),
        migrations.AddField(
            model_name='infostudent',
            name='start_social_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='дата назначения справки'),
        ),
    ]
