# Generated by Django 4.0 on 2023-03-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_profilestudent_remove_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudent',
            name='photo_student',
            field=models.FileField(default='default_img/default.png', upload_to='photo_student/%Y/%m.%d/', verbose_name='фото студента'),
        ),
    ]
