# Generated by Django 4.0 on 2023-03-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0011_alter_profilestudent_photo_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
